### ISSUE TITLE
Dependency Update

### ISSUE THREAD

**Issue by AndreasRaeder** [OpenSemanticLab/osw-python#36]
### Pydantic
Pydantic Version must be smaller then 2.0 when using OSW, need to be updated

![pydantic-version-error](https://github.com/OpenSemanticLab/osw-python/assets/91726609/91b88e05-fd90-4fea-8ea1-a5fe88d79425)

### Sympy
Additional dependency to `sympy` is required when using OSW

**Comment by simontaurus** [comment]
* pydantic v2 covered by #28 
* sympy was probably required by another code part
