### ISSUE TITLE
add custom limit to get_entities_from_osw in osw.data.import_utility

### ISSUE THREAD

**Issue by MatPoppFHG** [OpenSemanticLab/osw-python#43]
example necessity: 
there can be (far) more than 1000 rooms/users/etc, but media wiki queries have a standard limit of 1000. 

suggestion: 
entities = wtsite_obj.semantic_search(
        query=wt.SearchParam(
            query=f"[[HasType::Category:OSW{str(category_uuid).replace('-', '')}]]",
            limit=custom_limit,
            debug=debug,
        )

**Comment by LukasGold** [comment]
Was addressed in https://github.com/OpenSemanticLab/osw-python/commit/7ac25e1046d000c29fc02cf6a7fc907925bf5c8b
