### ISSUE TITLE
enh: Convenience wrapper for file download/upload

### ISSUE THREAD

**Issue by MatPoppFHG** [OpenSemanticLab/osw-python#50]
Currently a simple file-download takes 20-30 lines of code. This should be reduced to one line. Suggestion: 
``` python

import osw
from osw.express import file_download

file: osw.model.LocalFile = file_download("https://wiki-dev.open-semantic-lab.org/w/img_auth.php/3/3b/OSWe7d2664d26334d99a10093557bba77d5.txt")

df = pd.load_csv(file.raw)
```
What should happen in background: 
* parse correct osw instance from link 
* look up if credentials for instance exist
 *if yes => log in , go on 
 *if no => log in popup/prompt, with option to save credentials in local encrypted file
* update local model (WikiFile, LocalFile)

suggestion for funciton definition: 
``` python

def file_download(file: str , credentials_path = "usual/path/to/local/model", download_cache = "", osw_domain = None, return_binary = 
False) -> Union[path, bytesio]:
  """
  convenience function to quickly download a file from osw via a url that can conveniently be copied from the browser url line
  """
  if osw_domain is not None:
    ### prepend domain to file , else file must contain valid domain + osw id
```

**Comment by LukasGold** [comment]
What we would still need or is currently problematic: the reload of the model.entity classes generated by the controller imports leads to errors when serializing objects because the model loaded at the top by importing osw dont match the models imported by the reload (not pointing to the same memory entry).
Therefore, in my opinion, just as the controllers are part of osw-python, the (File) models should also be part of it

**Comment by SimonStier** [comment]
The actual file download can be condensed to 2 lines (see https://github.com/OpenSemanticLab/osw-python/blob/a30bb5e248bebcb75ec6e2c15f850f87b0f2b5cd/examples/file_upload_download.py#L60C1-L63C18)
```python
wf2 = osw_obj.load_entity("File:OSWe7d2664d26334d99a10093557bba77d5.txt").cast(WikiFileController, osw=osw_obj) 
LocalFileController(path="dummy2.txt").put_from(wf2)
```
So I guess the discussion is more about the osw initialization (login, schema download)

**Comment by LukasGold** [comment]
@MatPoppFHG A first draft is ready for review at: https://github.com/OpenSemanticLab/osw-python/compare/main...50-enh-osw-express
