### ISSUE TITLE
Consider renaming cred_fp and credentias_fp to cred_filepath in inter_osw_copy_page.py

### ISSUE THREAD

**Issue by simontaurus** [OpenSemanticLab/osw-python#69]
cred_filepath is used in the rest of the package

_Originally posted by @simontaurus in https://github.com/OpenSemanticLab/osw-python/pull/66#discussion_r1787945211_

**Comment by LukasGold** [comment]
Addressed with https://github.com/OpenSemanticLab/osw-python/commit/cafd31bbc0382c5c039268436979f8662fe6d01c

**Comment by LukasGold** [comment]
Applied to other repositories as well: https://github.com/OpenSemanticWorld-Packages/osw-package-maintenance/commit/9d1c3ccf933698a2e8529df07cd1c041ac4a36c9
